fos_user_registration_register:
    pattern: /inscription
    defaults: { _controller:FOSUserBundle:Registration:register}
    
fos_user_registration_check_email:
    pattern: /check_email
    defaults: { _controller:FOSUserBundle:Registration:checkEmail}

fos_user_registration_confirm:
    pattern: /confirm/{token}
    defaults: { _controller:FOSUserBundle:Registration:confirm}
    
fos_user_registration_confirmed:
    pattern: /confirmed
    defaults: { _controller:FOSUserBundle:Registration:confirmed}    