fos_user_resetting_request:
    pattern: /mot-de-passe-oublie
    defaults: { _controller: FOSUserBundle:Resetting:request}
    
fos_user_resetting_send_email:
    pattern: /send_email
    defaults: { _controller: FOSUserBundle:Resetting:sendEmail} 
    
fos_user_resetting_check_email:
    pattern: /check_email
    defaults: { _controller: FOSUserBundle:Resetting:checkEmail}   

fos_user_resetting_reset:
    pattern: /reset/{token}
    defaults: { _controller: FOSUserBundle:Resetting:reset}

 