calendrier:
    resource: "@CalendrierBundle/Resources/config/routing.yml"
    prefix:   /privee/calendrier

reservation:
    resource: "@ReservationBundle/Resources/config/routing.yml"
    prefix:   /privee/reservation

admin:
    resource: "@AdminBundle/Resources/config/routing.yml"
    prefix:   /admin

moniteur:
    resource: "@MoniteurBundle/Resources/config/routing.yml"
    prefix:   /moniteur

privee:
    resource: "@PriveeBundle/Resources/config/routing.yml"
    prefix:   /privee

public:
    resource: "@PublicBundle/Resources/config/routing.yml"
    prefix:   /

user:
    resource: "@UserBundle/Resources/config/routing.yml"
    prefix:   /
    
fos_user_security:
    resource: "@FOSUserBundle/Resources/config/routing/security.yml"    

fos_user_profile:
    resource: "@FOSUserBundle/Resources/config/routing/profil.yml"
    prefix: /privee/profile

fos_user_register:
    resource: "@FOSUserBundle/Resources/config/routing/registration.yml"
    prefix: /register

fos_user_resetting:
    resource: "@FOSUserBundle/Resources/config/routing/resetting.yml"
    prefix: /resetting

fos_user_change_password:
    resource: "@FOSUserBundle/Resources/config/routing/change_password.yml"
    prefix: /privee/profile    
