parameters:
    #calendrier.class: CalendrierBundle\Utils\AbstractCalendrier

services:
    calendrier_service:
        class: CalendrierBundle\Utils\CalendrierService
        #arguments: [%calendrier.class%]
