services:
    reservation_service:
        class: ReservationBundle\Service\ReservationService
        arguments: ["@doctrine.orm.entity_manager"]    
#    reservation.example:
#        class: ReservationBundle\Example
#        arguments: ["@service_id", "plain_value", "%parameter%"]
